### ISSUE TITLE
jquery error

### ISSUE THREAD

**Issue by ted423** [mantisbt-plugins/BBCodePlus#108]
the plugins newest version has this error in console(I tried 2.1.19 to 2.1.8 and 2.1.0)
and seems the 2.0.15 is the only version work for me
```
plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:108 Uncaught TypeError: Cannot read properties of undefined (reading 'safari')
    at init (plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:108:52)
    at HTMLTextAreaElement.<anonymous> (plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:542:4)
    at Function.each (jquery-2.2.4.min.js:2:2861)
    at n.fn.init.each (jquery-2.2.4.min.js:2:845)
    at $.fn.markItUp (plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:62:15)
    at HTMLDocument.<anonymous> (plugin_file.php?file=BBCodePlus/markitup-init.js:8:39)
    at i (jquery-2.2.4.min.js:2:27151)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2:27914)
    at Function.ready (jquery-2.2.4.min.js:2:29707)
    at HTMLDocument.J (jquery-2.2.4.min.js:2:29892)
init @ plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:108
（匿名） @ plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:542
each @ jquery-2.2.4.min.js:2
each @ jquery-2.2.4.min.js:2
$.fn.markItUp @ plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:62
（匿名） @ plugin_file.php?file=BBCodePlus/markitup-init.js:8
i @ jquery-2.2.4.min.js:2
fireWith @ jquery-2.2.4.min.js:2
ready @ jquery-2.2.4.min.js:2
J @ jquery-2.2.4.min.js:2
plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:359 Uncaught TypeError: Cannot read properties of undefined (reading 'msie')
    at fixIeBug (plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:359:19)
    at markup (plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:311:15)
    at plugin_file.php?file=BBCodePlus/markitup/jquery_markitup.js:176:32
```
and seem this function already remove
https://stackoverflow.com/questions/15011729/uncaught-typeerror-cannot-read-property-safari-of-undefined

the newest mantisbt use jquery 2.2.4

**Comment by ted423** [comment]
it seem is markitup's error
